---
# Name of the workflow
name: Checks
# Triggering event
on: [push]

# Jobs to be performed
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit Testing
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Linting
        run: docker-compose run --rm app sh -c "flake8"

